In [1]:
import numpy as np
import pandas as pd 


In [35]:

def rotated(array):    
    array=np.transpose(array)
    return np.flipud(array)

def flipped(array):
    return np.flipud(array)
def rolled(matrix, shift_amount):
    return np.roll(matrix, shift_amount, axis=1)

def noise(array):
    np.random.seed(0)
    noise= np.random.normal(0,0.5, array.shape)

    noisy_matrix= noise +array
    return noisy_matrix
        

def transform_image(array, shift):
    array= np.array(array)
    
    toret= {'rotated': rotated(array.copy()), 'flipped': flipped(array.copy()), 'rolled': rolled(array.copy(),shift), 'noised':noise(array.copy())}
    return toret


In [36]:
array= [ [0,1,1,1,0]
        ,[0,1,0,1,0]
        ,[0,1,1,1,0]
        ,[0,0,0,1,0]
        ,[0,0,0,1,0]]

res= transform_image(array,1)

In [38]:
res['noised']

array([[ 0.88202617,  1.2000786 ,  1.48936899,  2.1204466 ,  0.933779  ],
       [-0.48863894,  1.47504421, -0.0756786 ,  0.94839057,  0.20529925],
       [ 0.07202179,  1.72713675,  1.38051886,  1.06083751,  0.22193162],
       [ 0.16683716,  0.74703954, -0.10257913,  1.15653385, -0.42704787],
       [-1.27649491,  0.3268093 ,  0.4322181 ,  0.62891749,  1.13487731]])

In [29]:
array2= [ [0,1,1,1,0]
        ,[0,1,0,1,0]
        ,[0,1,1,1,0]
        ,[0,0,0,1,0]
        ,[0,0,0,1,0]]

array2= np.array(array2)

print(array2)

[[0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]]
