# Problem Statement
The assignment for Week 8 is to use Cython to speed up the code you wrote for assignment 2 (SPICE simulation). Note that the grade is not based on how much you speed up, but on how well you are able to analyze the code and explain your optimizations. Your documentation here is particularly important. Even if you try techniques but don't see a speedup, you should try to explain why it didn't work.

In [ ]:
#this one is straight from the week 2 assignment
import numpy as np
e= 5e3
class matrix_solver():
    def __init__(self, Ain, bin):
        self.A= Ain
        self.b= bin
        self.rowreduce=0
        self.sol=[]
        self.A, self.b= self.rearrange(self.A, self.b)
        
        
    def rearrange(self, matrix, b):
        len_row= len(matrix[0])
        len_column= len(matrix)
        if len_column>len_row:
            for row in range(len_row, len_column):
                for column in range(len_row):
                    matrix[0][column]+= matrix[row][column]
                b[0] += b[row]
            
        
        for diagonal in range(len_row):
            if matrix[diagonal][diagonal]== 0:
                for row in range(len_column):
                    if matrix[row][diagonal]!=0:
                        for column in range(len_row):
                            matrix[diagonal][column] += matrix[row][column]
                        b[diagonal] += b[row]
              
        return matrix, b

    def Row_reduce(self):
        
        lenrow= len(self.A[0])
        lencolumn= len(self.A)

        
        if lencolumn>=lenrow:
            for iter in range(lenrow):
                #normalizing
                for row_num in range(iter,lencolumn):

                    norm = self.A[row_num][iter]

                    if norm!=0:
                        for column_num in range(iter, lenrow):
                            self.A[row_num][column_num] /= norm
                        self.b[row_num] /= norm
                
                #row echelon
                for row_num in range(iter+1, lencolumn):

                    if self.A[row_num][iter]:
                        for column in range(iter, lenrow):
                            self.A[row_num][column] -= self.A[iter][column]
                        self.b[row_num] -= self.b[iter]
                self.rowreduce=1
        #rounding off
        for row in range(lencolumn):
            for column in range(lenrow):
                value_=self.A[row][column] 
                self.A[row][column]= round(value_.real,20)
        for value in range(lencolumn):
            value_= self.b[value]
            self.b[value]= round(value_.real,10)
        return [self.A,self.b]


    def transpose(self, matrix):
        len_= len(matrix)
        newA=[]
        for row in reversed(matrix):
            new_row=[]
            for num in reversed(row):
                new_row.append(num)
            newA.append(new_row)
        return newA


    def reversed_(self, matrix):
        c=[]
        for i in reversed(range(len(matrix))):
            c.append(matrix[i])
        return c

    def check_solvability(self, matrix, Bin):
        len_row= len(matrix[0])
        len_column= len(matrix)
        prod=1
        if len_column> len_row:
            for row in range(len_row):
                prod *= matrix[row][row]
                if prod ==0:
                    print("No solution")
                    return 0
                for column in range(len_row):
                    if matrix[row][column] != 0:
                        break
                    if  matrix[row][column] != 0 and column== len_row:
                        if Bin[row]==0:
                            print("Infinite solution")
                            return 0
                        else:
                            print("No solution")
                            return 0
            if Bin[len_row]!= 0:
                print("It is unsolvable!")
                return 0
            return 1
        elif len_column== len_row:
            prod=1
            for diagonal in range(len_row):
                prod *= matrix[diagonal][diagonal]
            if prod==0 and Bin[len_row-1]!=0:
                print("No solution")
                return 0
            elif prod==0 and Bin[len_row-1]==0:
                print("Infinite solution")
                return 0
            else:
                return 1
        else:
            print("Infinite solution")
            return 0
            
    def return_required_matrix(self, matrix, Bin):
        len_row= len(matrix[0])
        mat= []
        res= []
        for row in range(len_row):
            mat.append(matrix[row])
            res.append(Bin[row])
        return mat, res 

    def solve(self):
        for i in range(int(e)):
            self.A1, self.b2= self.rearrange(self.A.copy(), self.b.copy())
        self.A, self.b= self.rearrange(self.A, self.b)
        self.A, self.b= self.Row_reduce()
        
        if self.check_solvability(self.A, self.b):
            self.sol=[]
            self.A, self.b= self.return_required_matrix(self.A, self.b)
            self.A= self.transpose(self.A)
            self.b= self.reversed_(self.b)
            self.sol.append(self.b[0])
            len_= len(self.A[0])
            for row in range(1,len_):
                sum=0
                for column in range(0, row):
                    sum += (self.A[row][column])*(self.sol[column])
                self.sol.append(self.b[row]- sum)
            
            return self.reversed_(self.sol)

In [3]:
import numpy as np
class matrix_solver():
    def __init__(self, Ain, bin):
        self.A= Ain
        self.b= bin
        self.rowreduce=0
        self.sol=[]
        self.A, self.b= self.rearrange(self.A, self.b)
        
        
    def rearrange(self, matrix, b):
        len_row= len(matrix[0])
        len_column= len(matrix)
        if len_column>len_row:
            for row in range(len_row, len_column):
                for column in range(len_row):
                    matrix[0][column]+= matrix[row][column]
                b[0] += b[row]
            
        
        for diagonal in range(len_row):
            if matrix[diagonal][diagonal]== 0:
                for row in range(len_column):
                    if matrix[row][diagonal]!=0:
                        for column in range(len_row):
                            matrix[diagonal][column] += matrix[row][column]
                        b[diagonal] += b[row]
              
        return matrix, b

    def Row_reduce(self):
        
        lenrow= len(self.A[0])
        lencolumn= len(self.A)

        
        if lencolumn>=lenrow:
            for iter in range(lenrow):
                #normalizing
                for row_num in range(iter,lencolumn):

                    norm = self.A[row_num][iter]

                    if norm!=0:
                        for column_num in range(iter, lenrow):
                            self.A[row_num][column_num] /= norm
                        self.b[row_num] /= norm
                
                #row echelon
                for row_num in range(iter+1, lencolumn):

                    if self.A[row_num][iter]:
                        for column in range(iter, lenrow):
                            self.A[row_num][column] -= self.A[iter][column]
                        self.b[row_num] -= self.b[iter]
                self.rowreduce=1
        #rounding off
        for row in range(lencolumn):
            for column in range(lenrow):
                value_=self.A[row][column] 
                self.A[row][column]= round(value_.real,20)
        for value in range(lencolumn):
            value_= self.b[value]
            self.b[value]= round(value_.real,10)
        return [self.A,self.b]


    def transpose(self, matrix):
        len_= len(matrix)
        newA=[]
        for row in reversed(matrix):
            new_row=[]
            for num in reversed(row):
                new_row.append(num)
            newA.append(new_row)
        return newA


    def reversed_(self, matrix):
        c=[]
        for i in reversed(range(len(matrix))):
            c.append(matrix[i])
        return c

    def check_solvability(self, matrix, Bin):
        len_row= len(matrix[0])
        len_column= len(matrix)
        prod=1
        if len_column> len_row:
            for row in range(len_row):
                prod *= matrix[row][row]
                if prod ==0:
                    print("No solution")
                    return 0
                for column in range(len_row):
                    if matrix[row][column] != 0:
                        break
                    if  matrix[row][column] != 0 and column== len_row:
                        if Bin[row]==0:
                            print("Infinite solution")
                            return 0
                        else:
                            print("No solution")
                            return 0
            if Bin[len_row]!= 0:
                print("It is unsolvable!")
                return 0
            return 1
        elif len_column== len_row:
            prod=1
            for diagonal in range(len_row):
                prod *= matrix[diagonal][diagonal]
            if prod==0 and Bin[len_row-1]!=0:
                print("No solution")
                return 0
            elif prod==0 and Bin[len_row-1]==0:
                print("Infinite solution")
                return 0
            else:
                return 1
        else:
            print("Infinite solution")
            return 0
            
    def return_required_matrix(self, matrix, Bin):
        len_row= len(matrix[0])
        mat= []
        res= []
        for row in range(len_row):
            mat.append(matrix[row])
            res.append(Bin[row])
        return mat, res 

    def solve(self):
        self.A, self.b= self.rearrange(self.A, self.b)
        self.A, self.b= self.Row_reduce()
        
        if self.check_solvability(self.A, self.b):
            self.sol=[]
            self.A, self.b= self.return_required_matrix(self.A, self.b)
            self.A= self.transpose(self.A)
            self.b= self.reversed_(self.b)
            self.sol.append(self.b[0])
            len_= len(self.A[0])
            for row in range(1,len_):
                sum=0
                for column in range(0, row):
                    sum += (self.A[row][column])*(self.sol[column])
                self.sol.append(self.b[row]- sum)
            
            return self.reversed_(self.sol)

In [4]:
A= [[7, 6, 6, 6, 7, 5, 5, 4, 2, 2],
 [8, 6, 5, 6, 1, 1, 5, 4, 9, 2],
 [5, 3, 9, 8, 6, 4, 8, 4, 1, 3],
 [3, 5, 8, 8, 6, 5, 6, 4, 8, 1],
 [6, 7, 2, 1, 1, 1, 9, 1, 9, 3],
 [1, 8, 5, 8, 5, 1, 1, 5, 3, 0],
 [9, 9, 0, 3, 9, 3, 4, 2, 7, 5],
 [4, 1, 6, 8, 4, 8, 9, 2, 2, 9],
 [7, 6, 0, 0, 1, 3, 1, 2, 1, 9],
 [7, 0, 7, 7, 5, 5, 4, 1, 1, 0]]
B= [5850, 6088, 6339, 6624, 6847, 7016, 7275, 7586, 7750, 7906]

In [6]:
matrix_solver(A,B).solve()

[115.79830338963882,
 1432.499054032567,
 1467.8080783312425,
 598.5097274066972,
 -262.53347173409816,
 -162.4404953200319,
 -569.8157050538141,
 -2873.972531496633,
 -90.70757667758153,
 611.4156504996]

In [100]:
%timeit matrix_solver(c,d).solve()

print("THe above performace was from the week 2 Assingment!")

541 µs ± 5.05 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
THe above performace was from the week 2 Assingment!


So my first thought is to change all the types of the input into a defined one and all the other input types inside the class.
but first lets make the important setups.

In [88]:
%load_ext Cython

The Cython extension is already loaded. To reload it, use:
  %reload_ext Cython


In [96]:
%%cython --annotate

import cython
import numpy as np
cimport numpy as np

@cython.cdivision(True)
class cmatrix_solver1():
    def __init__(self,np.ndarray[np.double_t, ndim=2] Ain,np.ndarray[np.double_t, ndim=1] bin):
        cdef np.ndarray[np.double_t, ndim=2] A
        cdef np.ndarray[np.double_t, ndim=2] B
        cdef int rowreduce
        cdef np.ndarray[np.double_t, ndim=1] sol

        self.A= Ain
        self.b= bin
        self.rowreduce=0
        self.sol=np.array([])
        self.A, self.b= self.rearrange(self.A, self.b)
        
        
    def rearrange(self, np.ndarray[np.double_t, ndim=2] matrix, np.ndarray[np.double_t, ndim=1] b):
        cdef int len_row
        cdef int len_column
        
        len_row= len(matrix[0])
        len_column= len(matrix)
        if len_column>len_row:
            for row in range(len_row, len_column):
                for column in range(len_row):
                    matrix[0][column]+= matrix[row][column]
                b[0] += b[row]
            
        
        for diagonal in range(len_row):
            if matrix[diagonal][diagonal]== 0:
                for row in range(len_column):
                    if matrix[row][diagonal]!=0:
                        for column in range(len_row):
                            matrix[diagonal][column] += matrix[row][column]
                        b[diagonal] += b[row]
              
        return matrix, b

    def Row_reduce(self):
        cdef int lenrow
        cdef int lencolumn
        cdef float value_
        lenrow= len(self.A[0])
        lencolumn= len(self.A)

        
        if lencolumn>=lenrow:
            for iter in range(lenrow):
                #normalizing
                for row_num in range(iter,lencolumn):

                    norm = self.A[row_num][iter]

                    if norm!=0:
                        for column_num in range(iter, lenrow):
                            self.A[row_num][column_num] /= norm
                        self.b[row_num] /= norm
                
                #row echelon
                for row_num in range(iter+1, lencolumn):

                    if self.A[row_num][iter]:
                        for column in range(iter, lenrow):
                            self.A[row_num][column] -= self.A[iter][column]
                        self.b[row_num] -= self.b[iter]
                self.rowreduce=1
        #rounding off
        for row in range(lencolumn):
            for column in range(lenrow):
                value_=self.A[row][column] 
                self.A[row][column]= round(value_,20) 
        for value in range(lencolumn):
            value_= self.b[value]
            self.b[value]= round(value_,10)
        return [self.A,self.b]


    def transpose(self, np.ndarray[np.double_t, ndim=2] matrix):
        cdef int len_
        cdef np.ndarray[np.double_t, ndim=2] newA
        cdef np.ndarray[np.double_t, ndim=1] new_row
        cdef int row
        cdef int roww
        roww = len(matrix[0])
        len_= len(matrix)
        newA= np.array([matrix[0]], dtype= np.double)
        for rownum in reversed(range(1,len_)):
            
            new_row=np.array([], dtype= np.double)
            for iter in reversed(range(roww)):
                new_row=np.append(new_row,[matrix[rownum][iter]])
            newA= np.append(newA,[new_row], axis=0)
        return newA


    def reversed_(self, np.ndarray[np.double_t, ndim=1] matrix):
        cdef np.ndarray[np.double_t, ndim=1] c
        c=np.array([])
        for i in reversed(range(len(matrix))):
            c= np.append(c, [matrix[i]], axis=0) # c.append(matrix[i])
        return c

    def check_solvability(self, matrix, Bin):
    
        cdef int len_row
        cdef int len_column
        cdef float prod
        cdef int row
        cdef int column
        
        len_row= len(matrix[0])
        len_column= len(matrix)
        prod=1
        if len_column> len_row:
            for row in range(len_row):
                prod *= matrix[row][row]
                if prod ==0:
                    print("No solution")
                    return 0
                for column in range(len_row):
                    if matrix[row][column] != 0:
                        break
                    if  matrix[row][column] != 0 and column== len_row:
                        if Bin[row]==0:
                            print("Infinite solution")
                            return 0
                        else:
                            print("No solution")
                            return 0
            if Bin[len_row]!= 0:
                print("It is unsolvable!")
                return 0
            return 1
        elif len_column== len_row:
            prod=1
            for diagonal in range(len_row):
                prod *= matrix[diagonal][diagonal]
            if prod==0 and Bin[len_row-1]!=0:
                print("No solution")
                return 0
            elif prod==0 and Bin[len_row-1]==0:
                print("Infinite solution")
                return 0
            else:
                return 1
        else:
            print("Infinite solution")
            return 0
            
    def return_required_matrix( self, 
                                np.ndarray[np.double_t, ndim=2] matrix, 
                                np.ndarray[np.double_t, ndim=1] Bin
                                ):
        cdef int len_row
        len_row= len(matrix[0])
        cdef np.ndarray[np.double_t, ndim=2] mat
        cdef np.ndarray[np.double_t, ndim=1] res
        mat= np.array([matrix[0]])
        res= np.array([Bin[0]])
        
        for row in range(1,len_row):
            
            mat=np.append(mat,[matrix[row]], axis=0)
            res=np.append(res, [Bin[row]], axis=0)
        return mat, res 

    def solve(self):
        cdef int len_
        cdef int sum
        self.A, self.b= self.rearrange(self.A, self.b)
        self.A, self.b= self.Row_reduce()
        self.A= np.array(self.A)
        self.b= np.array(self.b)
 
        if self.check_solvability(self.A, self.b):
            self.sol=np.array([])
            self.A, self.b= self.return_required_matrix(self.A, self.b)
            self.A= self.transpose(self.A)
            self.b= self.reversed_(self.b)
            self.sol= np.append(self.sol,[self.b[0]])
            len_= len(self.A[0])
            
            for row in range(1,len_):
            
                sum=0
                for column in range(0, row):
                    sum += (self.A[row][column])*(self.sol[column])
                self.sol= np.append(self.sol,[self.b[row]-sum])  
            
            return self.reversed_(self.sol)

In [97]:
A=np.array(A, dtype= np.double)
B=np.array(B, dtype= np.double)
c= A.copy()
d= B.copy()

In [98]:
%timeit obj= cmatrix_solver1(c,d).solve()

730 µs ± 6.78 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [165]:
%%cython --annotate

import cython
import numpy as np
cimport numpy as np

@cython.cdivision(True)
def create_array(np.ndarray[np.double_t, ndim=2] A):
    cdef np.ndarray[np.double_t, ndim=2] my_array
    my_array= A
    for i in range(10):
        print(my_array[i])
    my_array= np.append(my_array,[np.array([7., 0., 7., 7., 5., 5., 4., 1., 1., 0.])], axis=0)
    print(" ")
    for i in range(11):
        print(my_array[i])

In [166]:
create_array(A)

[7. 6. 6. 6. 7. 5. 5. 4. 2. 2.]
[8. 6. 5. 6. 1. 1. 5. 4. 9. 2.]
[5. 3. 9. 8. 6. 4. 8. 4. 1. 3.]
[3. 5. 8. 8. 6. 5. 6. 4. 8. 1.]
[6. 7. 2. 1. 1. 1. 9. 1. 9. 3.]
[1. 8. 5. 8. 5. 1. 1. 5. 3. 0.]
[9. 9. 0. 3. 9. 3. 4. 2. 7. 5.]
[4. 1. 6. 8. 4. 8. 9. 2. 2. 9.]
[7. 6. 0. 0. 1. 3. 1. 2. 1. 9.]
[7. 0. 7. 7. 5. 5. 4. 1. 1. 0.]
 
[7. 6. 6. 6. 7. 5. 5. 4. 2. 2.]
[8. 6. 5. 6. 1. 1. 5. 4. 9. 2.]
[5. 3. 9. 8. 6. 4. 8. 4. 1. 3.]
[3. 5. 8. 8. 6. 5. 6. 4. 8. 1.]
[6. 7. 2. 1. 1. 1. 9. 1. 9. 3.]
[1. 8. 5. 8. 5. 1. 1. 5. 3. 0.]
[9. 9. 0. 3. 9. 3. 4. 2. 7. 5.]
[4. 1. 6. 8. 4. 8. 9. 2. 2. 9.]
[7. 6. 0. 0. 1. 3. 1. 2. 1. 9.]
[7. 0. 7. 7. 5. 5. 4. 1. 1. 0.]
[7. 0. 7. 7. 5. 5. 4. 1. 1. 0.]


In [7]:
%%cython --annotate

import cython
import numpy as np
cimport numpy as np
def sasa():
    cdef np.ndarray[np.double_t, ndim=1] a
    cdef np.ndarray[np.double_t, ndim=1] b
    a= np.array([1,2,3], dtype= float)
    b= np.array([4,5,6], dtype= float)
    print(np.append(a,[b]))

In [20]:
print("hello",A)

hello [[7. 6. 6. 6. 7. 5. 5. 4. 2. 2.]
 [8. 6. 5. 6. 1. 1. 5. 4. 9. 2.]
 [5. 3. 9. 8. 6. 4. 8. 4. 1. 3.]
 [3. 5. 8. 8. 6. 5. 6. 4. 8. 1.]
 [6. 7. 2. 1. 1. 1. 9. 1. 9. 3.]
 [1. 8. 5. 8. 5. 1. 1. 5. 3. 0.]
 [9. 9. 0. 3. 9. 3. 4. 2. 7. 5.]
 [4. 1. 6. 8. 4. 8. 9. 2. 2. 9.]
 [7. 6. 0. 0. 1. 3. 1. 2. 1. 9.]
 [7. 0. 7. 7. 5. 5. 4. 1. 1. 0.]]


In [78]:
solp= matrix_solver(A.copy(),B.copy()).solve()
obj= cmatrix_solver1(A.copy(),B.copy())
solc=obj.solve()


In [81]:
for i in range(len(solp)):
    print(solp[i], "<-->", solc[i])

115.79830338963882 <--> 29225186.714294434
1432.4990540325666 <--> 17984831.33331299
1467.8080783312425 <--> -12333481.399993896
598.5097274066974 <--> 369771.3307495117
-262.53347173409816 <--> -4908737.538208008
-162.4404953200319 <--> 3741475.727722168
-569.8157050538141 <--> -3278487.6354370117
-2873.972531496633 <--> 302009.0745544434
-90.70757667758153 <--> -151152.453125
611.4156504996 <--> 611.4156494141
